/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tasktoo;

import java.io.File;
import java.util.Scanner;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.DocumentBuilder;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import org.w3c.dom.Node;

public class App {
    public static void main(String[] args) {
        try {
          File inputFile = new File("./data.xml");
          DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
          DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
          Document doc = dBuilder.parse(inputFile);
          doc.getDocumentElement().normalize();
    
          Scanner scanner = new Scanner(System.in);
          System.out.println("Enter comma-separated list of field names to output:");
          String[] selectedFields = scanner.nextLine().split(",");
          for (String fieldName : selectedFields) {
            NodeList nodeList = doc.getElementsByTagName("field");
            for (int i = 0; i < nodeList.getLength(); i++) {
              Node node = nodeList.item(i);
              if (node.getNodeType() == Node.ELEMENT_NODE) {
                String nameAttr = node.getAttributes().getNamedItem("name").getNodeValue();
                if (nameAttr.equals(fieldName.trim())) {
                  String fieldValue = node.getTextContent();
                  System.out.println(fieldName + ": " + fieldValue);
                  break;
                }
              }
            }
          }
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
}
